# Generated by Django 2.2.6 on 2019-10-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
