# Generated by Django 2.2.6 on 2019-10-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20191018_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product',
            new_name='product_variant',
        ),
    ]
