# Generated by Django 2.2.6 on 2019-10-21 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userbillinginfo_date'),
        ('checkout', '0005_auto_20191019_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderInfo',
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('userbillinginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.UserBillingInfo')),
                ('date', models.DateField()),
            ],
            bases=('accounts.userbillinginfo',),
        ),
        migrations.AlterField(
            model_name='OrderLineItem',
            name='order_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.OrderInfo'),
        ),
    ]
