# Generated by Django 2.2.6 on 2019-10-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_quote_price_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionorder',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
