# Generated by Django 2.2.6 on 2019-10-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_commissionorder_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionorder',
            name='quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.CommissionOrder'),
        ),
    ]
