# Generated by Django 2.2.6 on 2019-11-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0007_auto_20191024_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionorder',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
