# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-11 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191010_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection_name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
