# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-11 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_current_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('current_series', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_series',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.Collection'),
        ),
    ]
